on: [push, pull_request]

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contributor listings in readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          columnsPerRow: 12
          imageSize: 75
